### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by nightblade9** [deengames-prototypes/seek-and-destroy#1]
Here's the sum total of stuff we need to finish before we can ship this (even if it's a tiny small game).

- [x] OAuth2, API project
- [ ] Deen value
- [ ] Database tech choice (#3)
- [ ] Pipeline to production (including tests) (#4)
- [ ] Incremental (harvest resources) (#2)
- [ ] Incremental: buildings, consumption per second) 
- [ ] Grid - explore, player/adversary per grid
- [ ] Units, attack and be attacked
- [ ] AI
- [ ] auto defenses (turrets etc.)
- [ ] Some way to endgame (beat adversaries, move, stuck, beat adversaries, ...)
- [ ] Architecture plan

**Comment by nightblade9** [comment]
Migrated to Trello
