### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by nightblade9** [deengames-prototypes/seek-and-destroy#5]
Here's the sum total of stuff we need to finish before we can ship this (even if it's a tiny small game).

- [x] OAuth2, API project (#4)
- [ ] Pipeline to production (including tests) (#2)
- [ ] Incremental (harvest resources, buildings, consumption per second) (#1)
- [ ] Grid - explore, player/adversary per grid
- [ ] Units, attack and be attacked
- [ ] AI
- [ ] auto defenses (turrets etc.)
- [ ] Some way to endgame (beat adversaries, move, stuck, beat adversaries, ...)
- [ ] Architecture plan
- [ ] Deen value

**Comment by nightblade9** [comment]
Migrating to new repo
